[project]
name = "plastinka-sales-predictior"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "darts>=0.34.0",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "ray[tune]>=2.44.0",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "torch>=2.6.0",
    "torchmetrics>=1.7.0",
]
