name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.10
    
    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv sync --extra dev --extra deployment --extra ml --extra cpu --extra dev
        uv pip install -e .
    
    - name: Run linting
      run: |
        uv run --extra dev --extra deployment --extra ml --extra cpu ruff check . --fix --exit-zero 2>&1 | tee lint_report.txt
        uv run --all-extras ruff format . || true
    - name: Upload lint report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: lint_report.txt
    - name: Add lint report to summary
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('lint_report.txt', 'utf8');
          core.summary.addRaw('### Ruff Lint Report\n');
          core.summary.addCodeBlock(report, 'text');
          await core.summary.write();
    
    - name: Run tests with coverage
      run: |
        uv run uv run --extra dev --extra deployment --extra ml --extra cpu pytest --cov=plastinka_sales_predictor --cov=deployment --cov-report=term-missing --cov-fail-under=60 --maxfail=10
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        fail_ci_if_error: false
