name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
    
    - name: Set up Python
      run: uv python install 3.10
    
    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv sync --all-extras
        uv pip install -e .
    
    - name: Run linting
      run: |
        uv run --all-extras ruff check . --exit-zero
        uv run --all-extras ruff format --check .
    
    - name: Debug paths and environment
      run: |
        echo "Current directory:"
        pwd
        echo "PYTHONPATH BEFORE fix:"
        echo $PYTHONPATH
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        echo "PYTHONPATH AFTER fix:"
        echo $PYTHONPATH
        echo "Python path AFTER fix:"
        python -c "import sys; print('\n'.join(sys.path))"
        echo "Testing import AFTER fix:"
        python -c "import deployment.app.models.api_models; print('✅ Success')" || echo "❌ Failed"
        echo "Testing uv run import AFTER fix:"
        uv run --all-extras python -c "import deployment.app.models.api_models; print('✅ Success')" || echo "❌ Failed"

    - name: Run tests with coverage
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        uv run --all-extras pytest --cov=plastinka_sales_predictor --cov=deployment --cov-report=term-missing --cov-fail-under=60 --maxfail=10
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        fail_ci_if_error: false
